environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
  - TARGET: i686-pc-windows-msvc
install:
  # Install Rust
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - set PATH=%PATH%;C:\Users\appveyor\.rustup\toolchains\stable-%TARGET%\bin
  # Install LLVM for MSVC
  - if %TARGET%==i686-pc-windows-msvc appveyor-retry appveyor DownloadFile http://releases.llvm.org/4.0.0/LLVM-4.0.0-win32.exe -FileName llvm-installer.exe
  - if %TARGET%==i686-pc-windows-msvc 7z x llvm-installer.exe -o"C:\Program Files (x86)\LLVM" -aoa
  - if %TARGET%==i686-pc-windows-msvc 7z x llvm-installer.exe -o"C:\Program Files\LLVM" -aoa
  - where clang
  - clang --version

  - rustc -V
  - cargo -V

build: false

test_script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc
